name: Release

on:
  push:
    branches:
      - main
      - backport/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Build packages
        run: pnpm exec turbo run build --filter='./packages/*'

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: github.ref_name == 'main'
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm (backports)
        id: changesets-backport
        if: startsWith(github.ref_name, 'backport/')
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
          publish: pnpm release:backports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
